### ISSUE TITLE
Osiris Error

### ISSUE THREAD

**Issue by Naneczka123** [Catterall/discord-pedo-hunting-tools#1]
Whenever i try 3rd option app crashes and leaves an error saying something is wrong in Osiris/Browser/(ip)/chrome.dll. How to fix that? 0x000012f

**Comment by Catterall** [comment]
Strange, I did not receive such errors. Could you tell me the following information please:
- After downloading the browser.zip file, did you extract the zip in the Osiris folder and did you touch anything within the new browser folder beforehand.

- What is your system's OS, version and architecture.

Furthermore, please contact me on discord (Manu Dei#8780). It is much easier to speak there than here.

**Comment by Catterall** [comment]
Issue resolved via discord.
Actions; Updated download link to google drive instead using browser file from my personal usage. Seems to have worked.
